/*
 * Copyright (c) 2025, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.wso2.carbon.siddhi.extensions.installer.core.util;

import org.wso2.carbon.siddhi.extensions.installer.core.config.mapping.models.ExtensionConfig;
import org.yaml.snakeyaml.DumperOptions;
import org.yaml.snakeyaml.Yaml;
import org.yaml.snakeyaml.representer.Representer;

import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

public class ProjectManifestWriter {

    static class ExtensionYamlEntry {
        public String name;
        public String version;
        public List<Map<String, String>> dependencies;

        public ExtensionYamlEntry(String name, String version, List<Map<String, String>> dependencies) {
            this.name = name;
            this.version = version;
            this.dependencies = dependencies;
        }
    }

    public static void writeYaml(Map<String, ExtensionConfig> extensions, String filePath) throws IOException {
        List<Map<String, Object>> yamlExtensions = new ArrayList<>();

        String siVersion = extractSIVersion();
        for (Map.Entry<String, ExtensionConfig> entry : extensions.entrySet()) {
            Map<String, Object> entryMap = new LinkedHashMap<>();
            ExtensionConfig config = entry.getValue();
            entryMap.put("name", config.getExtensionInfo().get("name"));
            entryMap.put("version", config.getExtensionInfo().get("version"));
            List<Map<String, String>> deps = config.getDependencies().stream()
                    .map(d -> {
                        Map<String, String> depMap = new LinkedHashMap<>();
                        depMap.put(d.getName(), d.getVersion());
                        return depMap;
                    })
                    .collect(Collectors.toList());
            entryMap.put("dependencies", deps);
            yamlExtensions.add(entryMap);
        }


        // Prepare SnakeYAML
        DumperOptions dumperOptions = new DumperOptions();
        dumperOptions.setDefaultFlowStyle(DumperOptions.FlowStyle.BLOCK);
        dumperOptions.setIndent(4);
        dumperOptions.setIndicatorIndent(2);
        dumperOptions.setPrettyFlow(true);
        dumperOptions.setDefaultScalarStyle(DumperOptions.ScalarStyle.DOUBLE_QUOTED);

        Yaml yaml = new Yaml(dumperOptions);

        try (FileWriter writer = new FileWriter(filePath)) {
            writer.write("# AUTO-GENERATED FILE. DO NOT MODIFY.\n\n");
            writer.write("# This file is auto-generated by SI for managing extensions.\n");
            writer.write("# It should not be modified by hand.\n\n");
            Map<String, Object> root = new HashMap<>();
            root.put("extensions", yamlExtensions);
            root.put("si-yaml-version", "1"); // TODO: constant
            root.put("si-version", siVersion);
            yaml.dump(root, writer);
        }
    }

    // TODO: move to a util if needed
    private static String extractSIVersion() throws IOException {
        Path versionFile = Paths.get(System.getProperty("carbon.home"))
                .resolve("bin")
                .resolve("version.txt");Ï
        String line = Files.readAllLines(versionFile).get(0);
        Pattern pattern = Pattern.compile("v(\\d+(?:\\.\\d+)+)");
        Matcher matcher = pattern.matcher(line);
        if (matcher.find()) {
            return matcher.group(1);
        } else {
            return "4.4.0"; // Initial version with the si.yaml // TODO: constant
        }
    }
}
